name: Upload to S3

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS
        env:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_s3_bucket: ${{ secrets.AWS_BUCKET }}
        run: |
          aws configure set aws_access_key_id $aws_key_id
          aws configure set aws_secret_access_key $aws_secret_access_key

      - name: Upload
        run: aws s3 cp ./images/test.png s3://$aws_s3_bucket/8/201220/android