name: Upload to S3

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env:
          aws-bucket: ${{ secrets.AWS_BUCKET }}

      - name: Upload
        run: aws s3 cp /images/test.png s3://$aws-bucket/8/201220/android